### ISSUE TITLE
Filtering is not allowed

### ISSUE THREAD

**Issue by burken-** [moonpyk/mvcdonutcaching#20]
When using MvcDonutCaching in combination with a Response.Filter the execution breaks.

E.g. I'm using a filter to minify the html output before it's sent to the client. This is done by: 

```
public class HtmlCompressFilterAttribute : ActionFilterAttribute
    {   
        public override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            if (filterContext.HttpContext.Response.ContentType.ToLower().Contains("text/html"))
            {
                filterContext.HttpContext.Response.Filter = new HtmlCompressorFilter(filterContext.HttpContext.Response.Filter);
                base.OnActionExecuting(filterContext);
            }
        }
    }
```

When using this in combination with MvcDonutCaching the code breaks with the error:

```
System.Web.HttpException (0x80004005): Filtering is not allowed.
   at System.Web.HttpResponse.set_Filter(Stream value)
```

**Comment by migig** [comment]
@Jeavon I'm having a similar problem to you... I need to update a cookie in a response filter, but of course it doesn't work on a cached action.

How did you solve your problem?

**Comment by AnkitDotNet** [comment]
Hi, I am also facing the same problem while implementing Donut caching.
 Filtering is not allowed. (System.Web.HttpResponse.set_Filter)
Stack Trace:

at System.Web.HttpResponse.set_Filter(Stream value)
   at Microsoft.VisualStudio.Web.PageInspector.Runtime.Tracing.PageInspectorHttpModule.OnPostRequestHandlerExecute(Object sender, EventArgs e)
   at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)..

If I use Debug= false then I don't get any issue but get a blank page. Any help highly appriciated.
