### ISSUE TITLE
 Action that takes ViewDataDictionary as parameter in Html.RenderAction breaks serialiser

### ISSUE THREAD

**Issue by jkpindahbc** [moonpyk/mvcdonutcaching#25]
Seems the data contract serializer does not work with ViewDataDictionary.  Is this true? Or am I doing something wrong?

ex: Html.RenderAction(MVC.Global.Footer(ViewData), true);

DevTrends.MvcDonutCaching.ActionSettingsSerialiser.Serialise(ActionSettings actionSettings) in c:\Users\moonpyk\Documents\Visual Studio 2012\Projects\mvcdonutcaching\DevTrends.MvcDonutCaching\ActionSettingsSerialiser.cs:22

Type 'System.Web.Mvc.ViewDataDictionary`1, Version=1.1.5.0, Culture=neutral, PublicKeyToken=null]]' with data contract name 'ArrayOfKeyValueOfstringanyType:http://schemas.microsoft.com/2003/10/Serialization/Arrays' is not expected. Consider using a DataContractResolver or add any types not known statically to the list of known types - for example, by using the KnownTypeAttribute attribute or by adding them to the list of known types passed to DataContractSerializer.

**Comment by migig** [comment]
@jkpindahbc I'm having [the same problem](https://github.com/moonpyk/mvcdonutcaching/issues/42). How did you solve it?

**Comment by moonpyk** [comment]
@migig Try to make a hash of your form values so that it becames a simple string

**Comment by migig** [comment]
@moonpyk thanks :smile:
