### ISSUE TITLE
problem with filterContext.HttpContext.Response.Filter in OnResultExecuted from ActionFilterAttribute 

### ISSUE THREAD

**Issue by huangjinshe** [moonpyk/mvcdonutcaching#40]
After use DonutOutputCache , if we get ``filterContext.HttpContext.Response.Filter`` in ``OnResultExecuted`` from ``ActionFilterAttribute ``
it will get type of : System.Web.HttpResponseStreamFilterSink

Why?

Bacause I need to record every page log. So I need to get it , but It will display error:
``Can not be an object of type "System.Web.HttpResponseStreamFilterSink" cast to type "Custom log class".``

**Comment by moonpyk** [comment]
This is due to the fact that MvcDonutCaching hooks into the MVC pipeline to eventually inject the action result (avoiding execution of the original action) with a cached one, you can did into the System.Web assembly to see how and why it does that.

**Comment by huangjinshe** [comment]
I can't understand.
It's all fine after I use ``Outputcache`` replace ``DonutOutputCache ``.
I'm using this way to record log :http://www.paulallen.org/blog/capture-and-log-requests-and-responses-aspnet-mvc-3

I hope you can fixed it , just let it normal like Outputcache(I only need log the record 1 time after I cache, but now, Outputcache can't record the log)

This is My setting on action:

``[OutputCache(Duration = 1 * 60 * 60 * 24)]``

**Comment by moonpyk** [comment]
I can't fix it

**Comment by huangjinshe** [comment]
Then open it please, At least let some one fixed it. I need to record the log at least 1 time in ActionFilter after use DonutOutputCache .

**Comment by moonpyk** [comment]
This is not an MvcDonutCaching issue but something due to your logging solution which is not adapted. I'm not there to fix your code.
