### ISSUE TITLE
Missing null check in KeyGenerator.cs

### ISSUE THREAD

**Issue by martingit** [moonpyk/mvcdonutcaching#57]
Null check for DataTokensKeyArea is missing on line 63.
```
63 if (routeData.DataTokens.ContainsKey(DataTokensKeyArea))
64 {
65    areaName = routeData.DataTokens[DataTokensKeyArea].ToString();
66 }

```
This causes is to crash in some cases (example using it with surfacecontrollers in umbraco).

It looks like you check for null on routedata values, but not on the datatoken.

Regards
Martin

**Comment by moonpyk** [comment]
Fixing this ASAP, releasing a new beta

**Comment by moonpyk** [comment]
@martingit it was already fixed and published as a Nuget prerelease
